// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iauzmetvyhkvuuleeemo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhdXptZXR2eWhrdnV1bGVlZW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMjkyMDIsImV4cCI6MjA1MjcwNTIwMn0.APD-olMWD3fxOY292kE6_Defa9gatnALJwV1V7zvcZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);